language: python
python:
- "3.4"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libboost1.55-all-dev
    - libboost1.55-tools-dev
    - g++-5
before_install:
#- find / -name libboost_python*.so
- which python
- printenv
- ls $VIRTUAL_ENV
- ls $PYENV_ROOT
- ls /usr/lib
#- >
#  echo -e "using python : 3.6 : $VIRTUAL_ENV/bin/python : $VIRTUAL_ENV/include : $VIRTUAL_ENV/lib ;" > ~/user-config.jam
- >
  echo -e "using python : 3.6 ;\nusing gcc : : ccache g++-5 : <cxxflags>-std=c++11 ;" > ~/user-config.jam
- cat ~/user-config.jam
- wget https://github.com/arvidn/libtorrent/archive/master.zip
- unzip master.zip
- cd libtorrent-master/bindings/python
#- python setup.py build --bjam
- bjam crypto=openssl
- ls -R
