language: python
python:
- "3.6"
addons:
  apt:
    packages:
    - libboost-dev
before_install:
- wget https://github.com/arvidn/libtorrent/archive/master.zip
- unzip master.zip
- cd libtorrent-master/bindings/python
- bjam
- ls