language: python
python:
- "3.6"
addons:
  apt:
    packages:
    - libboost-dev
    - libboost-tools-dev
before_install:
- which python
- echo "using python : 3.6 ;" >> ~/user-config.jam
- wget https://github.com/arvidn/libtorrent/archive/master.zip
- unzip master.zip
- cd libtorrent-master/bindings/python
- bjam
- ls -R