sudo: required
dist: trusty

language: python
python:
    - "3.5"

virtualenv:
  system_site_packages: true

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y python3-libtorrent python3-coverage

script: nosetests