sudo: required
dist: trusty

language: python
python:
    - "3.4"

virtualenv:
  system_site_packages: true

before_install:
    - sudo add-apt-repository ppa:deluge-team/ppa -y
    - sudo apt-get update -qq
    - sudo apt-get install -y python3-libtorrent

install:
    - python setup.py install

script: nosetests